package App_Ingles;

import java.awt.*;
import java.net.URL;
import javax.swing.*;

public class PnTeoria extends JPanel{
    
    public PnTeoria(){
        setLayout(new GridBagLayout());
        
        contenido();
    }
    
    private void contenido() {
        GridBagConstraints gbc = new GridBagConstraints();
        
        filaCero(gbc);
        filaUno(gbc);
        filaDos(gbc);
        filaTres(gbc);
    }
    
    private void filaCero(GridBagConstraints gbc){
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(15, 10, 0, 10);
        JPanel pnLetraA = new JPanel(new BorderLayout());
        pnLetraA.setBackground(Color.WHITE);
        pnLetraA.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbA = new JLabel("A a", SwingConstants.CENTER);
        lbA.setForeground(Color.BLACK);
        pnLetraA.add(lbA, BorderLayout.NORTH);
        JLabel lbEscribirA = new JLabel("ei", SwingConstants.CENTER);
        lbEscribirA.setForeground(Color.BLACK);
        pnLetraA.add(lbEscribirA, BorderLayout.CENTER);
        JButton btDecirA = new JButton("Pronunciacion");
        btDecirA.setBackground(Color.WHITE);
        btDecirA.setForeground(Color.BLACK);
        pnLetraA.add(btDecirA, BorderLayout.SOUTH);
        add(pnLetraA, gbc);
        
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraB = new JPanel(new BorderLayout());
        pnLetraB.setBackground(Color.WHITE);
        pnLetraB.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbB = new JLabel("B b", SwingConstants.CENTER);
        lbB.setForeground(Color.BLACK);
        pnLetraB.add(lbB, BorderLayout.NORTH);
        JLabel lbEscribirB = new JLabel("bi", SwingConstants.CENTER);
        lbEscribirB.setForeground(Color.BLACK);
        pnLetraB.add(lbEscribirB, BorderLayout.CENTER);
        JButton btDecirB = new JButton("Pronunciacion");
        btDecirB.setBackground(Color.WHITE);
        btDecirB.setForeground(Color.BLACK);
        pnLetraB.add(btDecirB, BorderLayout.SOUTH);
        add(pnLetraB, gbc);
        
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraC = new JPanel(new BorderLayout());
        pnLetraC.setBackground(Color.WHITE);
        pnLetraC.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbC = new JLabel("C c", SwingConstants.CENTER);
        lbC.setForeground(Color.BLACK);
        pnLetraC.add(lbC, BorderLayout.NORTH);
        JLabel lbEscribirC = new JLabel("si", SwingConstants.CENTER);
        lbEscribirC.setForeground(Color.BLACK);
        pnLetraC.add(lbEscribirC, BorderLayout.CENTER);
        JButton btDecirC = new JButton("Pronunciacion");
        btDecirC.setBackground(Color.WHITE);
        btDecirC.setForeground(Color.BLACK);
        pnLetraC.add(btDecirC, BorderLayout.SOUTH);
        add(pnLetraC, gbc);
        
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraD = new JPanel(new BorderLayout());
        pnLetraD.setBackground(Color.WHITE);
        pnLetraD.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbD = new JLabel("D d", SwingConstants.CENTER);
        lbD.setForeground(Color.BLACK);
        pnLetraD.add(lbD, BorderLayout.NORTH);
        JLabel lbEscribirD = new JLabel("di", SwingConstants.CENTER);
        lbEscribirD.setForeground(Color.BLACK);
        pnLetraD.add(lbEscribirD, BorderLayout.CENTER);
        JButton btDecirD = new JButton("Pronunciacion");
        btDecirD.setBackground(Color.WHITE);
        btDecirD.setForeground(Color.BLACK);
        pnLetraD.add(btDecirD, BorderLayout.SOUTH);
        add(pnLetraD, gbc);
        
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraE = new JPanel(new BorderLayout());
        pnLetraE.setBackground(Color.WHITE);
        pnLetraE.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbE = new JLabel("E e", SwingConstants.CENTER);
        lbE.setForeground(Color.BLACK);
        pnLetraE.add(lbE, BorderLayout.NORTH);
        JLabel lbEscribirE = new JLabel("i", SwingConstants.CENTER);
        lbEscribirE.setForeground(Color.BLACK);
        pnLetraE.add(lbEscribirE, BorderLayout.CENTER);
        JButton btDecirE = new JButton("Pronunciacion");
        btDecirE.setBackground(Color.WHITE);
        btDecirE.setForeground(Color.BLACK);
        pnLetraE.add(btDecirE, BorderLayout.SOUTH);
        add(pnLetraE, gbc);
        
        gbc.gridx = 5;
        gbc.gridy = 0;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraF = new JPanel(new BorderLayout());
        pnLetraF.setBackground(Color.WHITE);
        pnLetraF.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbF = new JLabel("F f", SwingConstants.CENTER);
        lbF.setForeground(Color.BLACK);
        pnLetraF.add(lbF, BorderLayout.NORTH);
        JLabel lbEscribirF = new JLabel("ef", SwingConstants.CENTER);
        lbEscribirF.setForeground(Color.BLACK);
        pnLetraF.add(lbEscribirF, BorderLayout.CENTER);
        JButton btDecirF = new JButton("Pronunciacion");
        btDecirF.setBackground(Color.WHITE);
        btDecirF.setForeground(Color.BLACK);
        pnLetraF.add(btDecirF, BorderLayout.SOUTH);
        add(pnLetraF, gbc);
        
        gbc.gridx = 6;
        gbc.gridy = 0;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraG = new JPanel(new BorderLayout());
        pnLetraG.setBackground(Color.WHITE);
        pnLetraG.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbG = new JLabel("G g", SwingConstants.CENTER);
        lbG.setForeground(Color.BLACK);
        pnLetraG.add(lbG, BorderLayout.NORTH);
        JLabel lbEscribirG = new JLabel("gi", SwingConstants.CENTER);
        lbEscribirG.setForeground(Color.BLACK);
        pnLetraG.add(lbEscribirG, BorderLayout.CENTER);
        JButton btDecirG = new JButton("Pronunciacion");
        btDecirG.setBackground(Color.WHITE);
        btDecirG.setForeground(Color.BLACK);
        pnLetraG.add(btDecirG, BorderLayout.SOUTH);
        add(pnLetraG, gbc);
    }
    
    private void filaUno(GridBagConstraints gbc){
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraH = new JPanel(new BorderLayout());
        pnLetraH.setBackground(Color.WHITE);
        pnLetraH.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbH = new JLabel("H h", SwingConstants.CENTER);
        lbH.setForeground(Color.BLACK);
        pnLetraH.add(lbH, BorderLayout.NORTH);
        JLabel lbEscribirH = new JLabel("eich", SwingConstants.CENTER);
        lbEscribirH.setForeground(Color.BLACK);
        pnLetraH.add(lbEscribirH, BorderLayout.CENTER);
        JButton btDecirH = new JButton("Pronunciacion");
        btDecirH.setBackground(Color.WHITE);
        btDecirH.setForeground(Color.BLACK);
        pnLetraH.add(btDecirH, BorderLayout.SOUTH);
        add(pnLetraH, gbc);
        
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraI = new JPanel(new BorderLayout());
        pnLetraI.setBackground(Color.WHITE);
        pnLetraI.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbI = new JLabel("I i", SwingConstants.CENTER);
        lbI.setForeground(Color.BLACK);
        pnLetraI.add(lbI, BorderLayout.NORTH);
        JLabel lbEscribirI = new JLabel("ai", SwingConstants.CENTER);
        lbEscribirI.setForeground(Color.BLACK);
        pnLetraI.add(lbEscribirI, BorderLayout.CENTER);
        JButton btDecirI = new JButton("Pronunciacion");
        btDecirI.setBackground(Color.WHITE);
        btDecirI.setForeground(Color.BLACK);
        pnLetraI.add(btDecirI, BorderLayout.SOUTH);
        add(pnLetraI, gbc);
        
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraJ = new JPanel(new BorderLayout());
        pnLetraJ.setBackground(Color.WHITE);
        pnLetraJ.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbJ = new JLabel("J j", SwingConstants.CENTER);
        lbJ.setForeground(Color.BLACK);
        pnLetraJ.add(lbJ, BorderLayout.NORTH);
        JLabel lbEscribirJ = new JLabel("jei", SwingConstants.CENTER);
        lbEscribirJ.setForeground(Color.BLACK);
        pnLetraJ.add(lbEscribirJ, BorderLayout.CENTER);
        JButton btDecirJ = new JButton("Pronunciacion");
        btDecirJ.setBackground(Color.WHITE);
        btDecirJ.setForeground(Color.BLACK);
        pnLetraJ.add(btDecirJ, BorderLayout.SOUTH);
        add(pnLetraJ, gbc);
        
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraK = new JPanel(new BorderLayout());
        pnLetraK.setBackground(Color.WHITE);
        pnLetraK.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbK = new JLabel("K k", SwingConstants.CENTER);
        lbK.setForeground(Color.BLACK);
        pnLetraK.add(lbH, BorderLayout.NORTH);
        JLabel lbEscribirK = new JLabel("kei", SwingConstants.CENTER);
        lbEscribirK.setForeground(Color.BLACK);
        pnLetraK.add(lbEscribirK, BorderLayout.CENTER);
        JButton btDecirK = new JButton("Pronunciacion");
        btDecirK.setBackground(Color.WHITE);
        btDecirK.setForeground(Color.BLACK);
        pnLetraK.add(btDecirK, BorderLayout.SOUTH);
        add(pnLetraK, gbc);
        
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraL = new JPanel(new BorderLayout());
        pnLetraL.setBackground(Color.WHITE);
        pnLetraL.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbL = new JLabel("L l", SwingConstants.CENTER);
        lbL.setForeground(Color.BLACK);
        pnLetraL.add(lbL, BorderLayout.NORTH);
        JLabel lbEscribirL = new JLabel("el", SwingConstants.CENTER);
        lbEscribirL.setForeground(Color.BLACK);
        pnLetraL.add(lbEscribirL, BorderLayout.CENTER);
        JButton btDecirL = new JButton("Pronunciacion");
        btDecirL.setBackground(Color.WHITE);
        btDecirL.setForeground(Color.BLACK);
        pnLetraL.add(btDecirL, BorderLayout.SOUTH);
        add(pnLetraL, gbc);
        
        gbc.gridx = 5;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraM = new JPanel(new BorderLayout());
        pnLetraM.setBackground(Color.WHITE);
        pnLetraM.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbM = new JLabel("M m", SwingConstants.CENTER);
        lbM.setForeground(Color.BLACK);
        pnLetraM.add(lbM, BorderLayout.NORTH);
        JLabel lbEscribirM = new JLabel("em", SwingConstants.CENTER);
        lbEscribirM.setForeground(Color.BLACK);
        pnLetraM.add(lbEscribirM, BorderLayout.CENTER);
        JButton btDecirM = new JButton("Pronunciacion");
        btDecirM.setBackground(Color.WHITE);
        btDecirM.setForeground(Color.BLACK);
        pnLetraM.add(btDecirM, BorderLayout.SOUTH);
        add(pnLetraM, gbc);
        
        gbc.gridx = 6;
        gbc.gridy = 1;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraN = new JPanel(new BorderLayout());
        pnLetraN.setBackground(Color.WHITE);
        pnLetraN.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbN = new JLabel("N n", SwingConstants.CENTER);
        lbN.setForeground(Color.BLACK);
        pnLetraN.add(lbN, BorderLayout.NORTH);
        JLabel lbEscribirN = new JLabel("en", SwingConstants.CENTER);
        lbEscribirN.setForeground(Color.BLACK);
        pnLetraN.add(lbEscribirN, BorderLayout.CENTER);
        JButton btDecirN = new JButton("Pronunciacion");
        btDecirN.setBackground(Color.WHITE);
        btDecirN.setForeground(Color.BLACK);
        pnLetraN.add(btDecirN, BorderLayout.SOUTH);
        add(pnLetraN, gbc);
    }
    
    private void filaDos(GridBagConstraints gbc){
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraO = new JPanel(new BorderLayout());
        pnLetraO.setBackground(Color.WHITE);
        pnLetraO.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbO = new JLabel("O o", SwingConstants.CENTER);
        lbO.setForeground(Color.BLACK);
        pnLetraO.add(lbO, BorderLayout.NORTH);
        JLabel lbEscribirO = new JLabel("ou", SwingConstants.CENTER);
        lbEscribirO.setForeground(Color.BLACK);
        pnLetraO.add(lbEscribirO, BorderLayout.CENTER);
        JButton btDecirO = new JButton("Pronunciacion");
        btDecirO.setBackground(Color.WHITE);
        btDecirO.setForeground(Color.BLACK);
        pnLetraO.add(btDecirO, BorderLayout.SOUTH);
        add(pnLetraO, gbc);
        
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraP = new JPanel(new BorderLayout());
        pnLetraP.setBackground(Color.WHITE);
        pnLetraP.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbP = new JLabel("P p", SwingConstants.CENTER);
        lbP.setForeground(Color.BLACK);
        pnLetraP.add(lbP, BorderLayout.NORTH);
        JLabel lbEscribirP = new JLabel("pi", SwingConstants.CENTER);
        lbEscribirP.setForeground(Color.BLACK);
        pnLetraP.add(lbEscribirP, BorderLayout.CENTER);
        JButton btDecirP = new JButton("Pronunciacion");
        btDecirP.setBackground(Color.WHITE);
        btDecirP.setForeground(Color.BLACK);
        pnLetraP.add(btDecirP, BorderLayout.SOUTH);
        add(pnLetraP, gbc);
        
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraQ = new JPanel(new BorderLayout());
        pnLetraQ.setBackground(Color.WHITE);
        pnLetraQ.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbQ = new JLabel("Q q", SwingConstants.CENTER);
        lbQ.setForeground(Color.BLACK);
        pnLetraQ.add(lbQ, BorderLayout.NORTH);
        JLabel lbEscribirQ = new JLabel("kiu", SwingConstants.CENTER);
        lbEscribirQ.setForeground(Color.BLACK);
        pnLetraQ.add(lbEscribirQ, BorderLayout.CENTER);
        JButton btDecirQ = new JButton("Pronunciacion");
        btDecirQ.setBackground(Color.WHITE);
        btDecirQ.setForeground(Color.BLACK);
        pnLetraQ.add(btDecirQ, BorderLayout.SOUTH);
        add(pnLetraQ, gbc);
        
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraR = new JPanel(new BorderLayout());
        pnLetraR.setBackground(Color.WHITE);
        pnLetraR.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbR = new JLabel("R r", SwingConstants.CENTER);
        lbR.setForeground(Color.BLACK);
        pnLetraR.add(lbR, BorderLayout.NORTH);
        JLabel lbEscribirR = new JLabel("ar", SwingConstants.CENTER);
        lbEscribirR.setForeground(Color.BLACK);
        pnLetraR.add(lbEscribirR, BorderLayout.CENTER);
        JButton btDecirR = new JButton("Pronunciacion");
        btDecirR.setBackground(Color.WHITE);
        btDecirR.setForeground(Color.BLACK);
        pnLetraR.add(btDecirR, BorderLayout.SOUTH);
        add(pnLetraR, gbc);
        
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraS = new JPanel(new BorderLayout());
        pnLetraS.setBackground(Color.WHITE);
        pnLetraS.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbS = new JLabel("S s", SwingConstants.CENTER);
        lbS.setForeground(Color.BLACK);
        pnLetraS.add(lbS, BorderLayout.NORTH);
        JLabel lbEscribirS = new JLabel("es", SwingConstants.CENTER);
        lbEscribirS.setForeground(Color.BLACK);
        pnLetraS.add(lbEscribirS, BorderLayout.CENTER);
        JButton btDecirS = new JButton("Pronunciacion");
        btDecirS.setBackground(Color.WHITE);
        btDecirS.setForeground(Color.BLACK);
        pnLetraS.add(btDecirS, BorderLayout.SOUTH);
        add(pnLetraS, gbc);
        
        gbc.gridx = 5;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraT = new JPanel(new BorderLayout());
        pnLetraT.setBackground(Color.WHITE);
        pnLetraT.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbT = new JLabel("T t", SwingConstants.CENTER);
        lbT.setForeground(Color.BLACK);
        pnLetraT.add(lbT, BorderLayout.NORTH);
        JLabel lbEscribirT = new JLabel("ti", SwingConstants.CENTER);
        lbEscribirT.setForeground(Color.BLACK);
        pnLetraT.add(lbEscribirT, BorderLayout.CENTER);
        JButton btDecirT = new JButton("Pronunciacion");
        btDecirT.setBackground(Color.WHITE);
        btDecirT.setForeground(Color.BLACK);
        pnLetraT.add(btDecirT, BorderLayout.SOUTH);
        add(pnLetraT, gbc);
        
        gbc.gridx = 6;
        gbc.gridy = 2;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraU = new JPanel(new BorderLayout());
        pnLetraU.setBackground(Color.WHITE);
        pnLetraU.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbU = new JLabel("U u", SwingConstants.CENTER);
        lbU.setForeground(Color.BLACK);
        pnLetraU.add(lbU, BorderLayout.NORTH);
        JLabel lbEscribirU = new JLabel("iu", SwingConstants.CENTER);
        lbEscribirU.setForeground(Color.BLACK);
        pnLetraU.add(lbEscribirU, BorderLayout.CENTER);
        JButton btDecirU = new JButton("Pronunciacion");
        btDecirU.setBackground(Color.WHITE);
        btDecirU.setForeground(Color.BLACK);
        pnLetraU.add(btDecirU, BorderLayout.SOUTH);
        add(pnLetraU, gbc);
    }
    
    private void filaTres(GridBagConstraints gbc){
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraV = new JPanel(new BorderLayout());
        pnLetraV.setBackground(Color.WHITE);
        pnLetraV.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbV = new JLabel("V v", SwingConstants.CENTER);
        lbV.setForeground(Color.BLACK);
        pnLetraV.add(lbV, BorderLayout.NORTH);
        JLabel lbEscribirV = new JLabel("vi", SwingConstants.CENTER);
        lbEscribirV.setForeground(Color.BLACK);
        pnLetraV.add(lbEscribirV, BorderLayout.CENTER);
        JButton btDecirV = new JButton("Pronunciacion");
        btDecirV.setBackground(Color.WHITE);
        btDecirV.setForeground(Color.BLACK);
        pnLetraV.add(btDecirV, BorderLayout.SOUTH);
        add(pnLetraV, gbc);
        
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraW = new JPanel(new BorderLayout());
        pnLetraW.setBackground(Color.WHITE);
        pnLetraW.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbW = new JLabel("W w", SwingConstants.CENTER);
        lbW.setForeground(Color.BLACK);
        pnLetraW.add(lbW, BorderLayout.NORTH);
        JLabel lbEscribirW = new JLabel("dabliu", SwingConstants.CENTER);
        lbEscribirW.setForeground(Color.BLACK);
        pnLetraW.add(lbEscribirW, BorderLayout.CENTER);
        JButton btDecirW = new JButton("Pronunciacion");
        btDecirW.setBackground(Color.WHITE);
        btDecirW.setForeground(Color.BLACK);
        pnLetraW.add(btDecirW, BorderLayout.SOUTH);
        add(pnLetraW, gbc);
        
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraX = new JPanel(new BorderLayout());
        pnLetraX.setBackground(Color.WHITE);
        pnLetraX.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbX = new JLabel("X x", SwingConstants.CENTER);
        lbX.setForeground(Color.BLACK);
        pnLetraX.add(lbX, BorderLayout.NORTH);
        JLabel lbEscribirX = new JLabel("ecs", SwingConstants.CENTER);
        lbEscribirX.setForeground(Color.BLACK);
        pnLetraX.add(lbEscribirX, BorderLayout.CENTER);
        JButton btDecirX = new JButton("Pronunciacion");
        btDecirX.setBackground(Color.WHITE);
        btDecirX.setForeground(Color.BLACK);
        pnLetraX.add(btDecirX, BorderLayout.SOUTH);
        add(pnLetraX, gbc);
        
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraY = new JPanel(new BorderLayout());
        pnLetraY.setBackground(Color.WHITE);
        pnLetraY.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbY = new JLabel("Y y", SwingConstants.CENTER);
        lbY.setForeground(Color.BLACK);
        pnLetraY.add(lbY, BorderLayout.NORTH);
        JLabel lbEscribirY = new JLabel("uai", SwingConstants.CENTER);
        lbEscribirY.setForeground(Color.BLACK);
        pnLetraY.add(lbEscribirY, BorderLayout.CENTER);
        JButton btDecirY = new JButton("Pronunciacion");
        btDecirY.setBackground(Color.WHITE);
        btDecirY.setForeground(Color.BLACK);
        pnLetraY.add(btDecirY, BorderLayout.SOUTH);
        add(pnLetraY, gbc);
        
        gbc.gridx = 5;
        gbc.gridy = 3;
        gbc.gridwidth = 1;
        gbc.gridheight = 1;
        gbc.weighty = 0.0;
        gbc.fill = GridBagConstraints.BOTH;
        JPanel pnLetraZ = new JPanel(new BorderLayout());
        pnLetraZ.setBackground(Color.WHITE);
        pnLetraV.setBorder(BorderFactory.createLineBorder(Color.BLUE));
        JLabel lbZ = new JLabel("Z z", SwingConstants.CENTER);
        lbZ.setForeground(Color.BLACK);
        pnLetraZ.add(lbZ, BorderLayout.NORTH);
        JLabel lbEscribirZ = new JLabel("zed", SwingConstants.CENTER);
        lbEscribirZ.setForeground(Color.BLACK);
        pnLetraZ.add(lbEscribirZ, BorderLayout.CENTER);
        JButton btDecirZ = new JButton("Pronunciacion");
        btDecirZ.setBackground(Color.WHITE);
        btDecirZ.setForeground(Color.BLACK);
        pnLetraZ.add(btDecirZ, BorderLayout.SOUTH);
        add(pnLetraZ, gbc);
    }
    
    @Override
    public void paintComponent(Graphics g){
        URL url = getClass().getResource("/Recursos/imgF1.jpg");
        ImageIcon icono = new ImageIcon(url);
        Image img = icono.getImage();
        super.paintComponent(g);
        if(img != null)
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
    }
    
}
